blank_issues_enabled: true
contact_links:
  - name: Support Discussions
    url: https://github.com/NetworkBuild3r/manyfold-ai/discussions
    about: Having trouble, but can't pin it down to a specific bug? Open a discussion on this repository.
