"""packs: resolution units, unit mesh sets, decision evidence, classification cache + overrides

Revision ID: 0004_packs
Revises: 0005_materialize
Create Date: 2026-10-03

INIT-032/SPEC-010 + SPEC-011. Chained after 0005_materialize (merged first) to keep one head.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from forge.db.enums import PACK_CATEGORIES

revision: str = "0004_packs"
down_revision: str | Sequence[str] | None = "0005_materialize"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CATS = ", ".join("'" + c.replace("'", "''") + "'" for c in PACK_CATEGORIES)


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE pack_units (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            unit_key text NOT NULL UNIQUE,
            kind text NOT NULL CHECK (kind IN ('archive', 'loose')),
            path text NOT NULL,
            model_root text,
            coloc_root text,
            root_container_id bigint REFERENCES containers(id) ON DELETE CASCADE,
            present boolean NOT NULL DEFAULT true,
            complete boolean NOT NULL DEFAULT false,
            file_count integer NOT NULL DEFAULT 0,
            image_count integer NOT NULL DEFAULT 0,
            mesh_count integer NOT NULL DEFAULT 0,
            mesh_bytes bigint NOT NULL DEFAULT 0,
            tri_sum bigint NOT NULL DEFAULT 0,
            set_hash text,
            pack_id bigint REFERENCES packs(id) ON DELETE SET NULL,
            role pack_container_role,
            updated_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_pack_units_pack_id ON pack_units (pack_id)")
    op.execute("CREATE INDEX ix_pack_units_model_root ON pack_units (model_root)")
    op.execute(
        """
        CREATE TABLE pack_unit_meshes (
            unit_id bigint NOT NULL REFERENCES pack_units(id) ON DELETE CASCADE,
            blob_sha text NOT NULL REFERENCES blobs(sha256) ON DELETE CASCADE,
            PRIMARY KEY (unit_id, blob_sha)
        )
        """
    )
    op.execute("CREATE INDEX ix_pack_unit_meshes_blob ON pack_unit_meshes (blob_sha)")
    op.execute(
        """
        CREATE TABLE pack_unit_sources (
            unit_id bigint NOT NULL REFERENCES pack_units(id) ON DELETE CASCADE,
            source_file_id bigint NOT NULL REFERENCES source_files(id) ON DELETE CASCADE,
            PRIMARY KEY (unit_id, source_file_id)
        )
        """
    )
    op.execute("CREATE INDEX ix_pack_unit_sources_file ON pack_unit_sources (source_file_id)")

    op.execute("ALTER TABLE pack_decisions ALTER COLUMN container_a DROP NOT NULL")
    op.execute("ALTER TABLE pack_decisions ALTER COLUMN container_b DROP NOT NULL")
    op.execute(
        """
        ALTER TABLE pack_decisions
            ADD COLUMN unit_a bigint REFERENCES pack_units(id) ON DELETE CASCADE,
            ADD COLUMN unit_b bigint REFERENCES pack_units(id) ON DELETE CASCADE,
            ADD COLUMN key_a text,
            ADD COLUMN key_b text,
            ADD COLUMN prompt_hash text,
            ADD COLUMN needs_review boolean NOT NULL DEFAULT false,
            ADD COLUMN error text,
            ADD COLUMN evidence jsonb
        """
    )
    op.execute("CREATE INDEX ix_pack_decisions_fingerprint ON pack_decisions (input_fingerprint)")
    op.execute("CREATE INDEX ix_pack_decisions_kind ON pack_decisions (kind)")

    op.execute(
        """
        ALTER TABLE packs
            ADD COLUMN tags text[] NOT NULL DEFAULT '{}',
            ADD COLUMN review_reasons text[] NOT NULL DEFAULT '{}',
            ADD COLUMN unit_count integer NOT NULL DEFAULT 0,
            ADD COLUMN mesh_count integer NOT NULL DEFAULT 0,
            ADD COLUMN mesh_bytes bigint NOT NULL DEFAULT 0,
            ADD COLUMN classify_fingerprint text,
            ADD COLUMN classify_confidence numeric(5, 4),
            ADD COLUMN classified_at timestamptz,
            ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now()
        """
    )

    op.execute(
        f"""
        CREATE TABLE classify_decisions (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            input_fingerprint text NOT NULL,
            prompt_hash text NOT NULL,
            model text,
            verdict text NOT NULL CHECK (verdict IN ('ok', 'unsure')),
            decided_by text NOT NULL CHECK (decided_by IN ('deterministic', 'llm')),
            category text CHECK (category IS NULL OR category IN ({_CATS})),
            display_name text,
            creator text,
            source_tag text,
            tags text[] NOT NULL DEFAULT '{{}}',
            review_reasons text[] NOT NULL DEFAULT '{{}}',
            confidence numeric(5, 4),
            error text,
            evidence jsonb,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_classify_decisions_fp ON classify_decisions "
        "(input_fingerprint, prompt_hash)"
    )
    op.execute(
        f"""
        CREATE TABLE classify_overrides (
            unit_key text PRIMARY KEY,
            category text CHECK (category IS NULL OR category IN ({_CATS})),
            name text,
            creator text,
            tags text[],
            note text,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE classify_overrides")
    op.execute("DROP TABLE classify_decisions")
    op.execute(
        """
        ALTER TABLE packs
            DROP COLUMN tags, DROP COLUMN review_reasons, DROP COLUMN unit_count,
            DROP COLUMN mesh_count, DROP COLUMN mesh_bytes, DROP COLUMN classify_fingerprint,
            DROP COLUMN classify_confidence, DROP COLUMN classified_at, DROP COLUMN updated_at
        """
    )
    op.execute("DROP INDEX ix_pack_decisions_kind")
    op.execute("DROP INDEX ix_pack_decisions_fingerprint")
    op.execute(
        """
        ALTER TABLE pack_decisions
            DROP COLUMN unit_a, DROP COLUMN unit_b, DROP COLUMN key_a, DROP COLUMN key_b,
            DROP COLUMN prompt_hash, DROP COLUMN needs_review, DROP COLUMN error,
            DROP COLUMN evidence
        """
    )
    op.execute("DELETE FROM pack_decisions WHERE container_a IS NULL OR container_b IS NULL")
    op.execute("ALTER TABLE pack_decisions ALTER COLUMN container_a SET NOT NULL")
    op.execute("ALTER TABLE pack_decisions ALTER COLUMN container_b SET NOT NULL")
    op.execute("DROP TABLE pack_unit_sources")
    op.execute("DROP TABLE pack_unit_meshes")
    op.execute("DROP TABLE pack_units")
