"""materialize: plan, work units (claim table), planned blobs, packs, files

Revision ID: 0005_materialize
Revises: 0002_sweep_progress
Create Date: 2026-10-03

INIT-032/SPEC-012. Materialize state references catalog ids (packs, containers, blobs) as plain
columns — no foreign keys into the catalog, so a re-sweep that purges nested containers can never
be blocked by an old plan. Rows cascade from ``materialize_plans``.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0005_materialize"
down_revision: str | Sequence[str] | None = "0002_sweep_progress"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_UPGRADE = """
CREATE TABLE materialize_plans (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamptz NOT NULL DEFAULT now(),
    status        text NOT NULL DEFAULT 'active'
                  CONSTRAINT ck_materialize_plans_status CHECK (status IN ('active', 'superseded')),
    layout        text NOT NULL
                  CONSTRAINT ck_materialize_plans_layout CHECK (layout IN ('tree', 'flat')),
    tool_version  text NOT NULL,
    packs         integer NOT NULL DEFAULT 0,
    files         bigint NOT NULL DEFAULT 0,
    blobs         bigint NOT NULL DEFAULT 0,
    unique_bytes  bigint NOT NULL DEFAULT 0,
    linked_bytes  bigint NOT NULL DEFAULT 0,
    missing_blobs bigint NOT NULL DEFAULT 0,
    free_bytes    bigint,
    totals        text
);

CREATE TABLE materialize_units (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id           bigint NOT NULL REFERENCES materialize_plans(id) ON DELETE CASCADE,
    kind              text NOT NULL
                      CONSTRAINT ck_materialize_units_kind CHECK (kind IN ('loose', 'archive')),
    root_container_id bigint,
    status            text NOT NULL DEFAULT 'pending'
                      CONSTRAINT ck_materialize_units_status
                      CHECK (status IN ('pending', 'claimed', 'done', 'failed')),
    claimed_by        text,
    claimed_at        timestamptz,
    attempts          integer NOT NULL DEFAULT 0,
    finished_at       timestamptz,
    blobs             integer NOT NULL DEFAULT 0,
    bytes             bigint NOT NULL DEFAULT 0,
    source_bytes      bigint NOT NULL DEFAULT 0,
    error             text
);
CREATE INDEX ix_materialize_units_pending ON materialize_units (plan_id, kind, id)
    WHERE status = 'pending';
CREATE INDEX ix_materialize_units_claimed ON materialize_units (plan_id, claimed_at)
    WHERE status = 'claimed';

CREATE TABLE materialize_blobs (
    plan_id           bigint NOT NULL REFERENCES materialize_plans(id) ON DELETE CASCADE,
    sha256            text NOT NULL
                      CONSTRAINT ck_materialize_blobs_sha CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    size              bigint NOT NULL,
    kind              text NOT NULL,
    source_kind       text NOT NULL
                      CONSTRAINT ck_materialize_blobs_source_kind
                      CHECK (source_kind IN ('loose', 'archive', 'missing')),
    source_path       text,
    source_size       bigint,
    source_mtime      timestamptz,
    root_container_id bigint,
    member_chain      text[],
    unit_id           bigint REFERENCES materialize_units(id) ON DELETE CASCADE,
    state             text NOT NULL DEFAULT 'pending'
                      CONSTRAINT ck_materialize_blobs_state
                      CHECK (state IN ('pending', 'done', 'failed', 'missing')),
    method            text,
    error             text,
    finished_at       timestamptz,
    PRIMARY KEY (plan_id, sha256)
);
CREATE INDEX ix_materialize_blobs_unit ON materialize_blobs (unit_id);

CREATE TABLE materialize_packs (
    plan_id     bigint NOT NULL REFERENCES materialize_plans(id) ON DELETE CASCADE,
    pack_id     bigint NOT NULL,
    category    text NOT NULL,
    name        text,
    dir         text NOT NULL,
    files       integer NOT NULL DEFAULT 0,
    bytes       bigint NOT NULL DEFAULT 0,
    missing     integer NOT NULL DEFAULT 0,
    status      text NOT NULL DEFAULT 'pending'
                CONSTRAINT ck_materialize_packs_status
                CHECK (status IN ('pending', 'claimed', 'done', 'incomplete', 'failed')),
    claimed_by  text,
    claimed_at  timestamptz,
    attempts    integer NOT NULL DEFAULT 0,
    finished_at timestamptz,
    error       text,
    counts      text,
    meta        text,
    PRIMARY KEY (plan_id, pack_id),
    CONSTRAINT uq_materialize_packs_dir UNIQUE (plan_id, dir)
);
CREATE INDEX ix_materialize_packs_pending ON materialize_packs (plan_id, pack_id)
    WHERE status = 'pending';

CREATE TABLE materialize_files (
    plan_id      bigint NOT NULL,
    pack_id      bigint NOT NULL,
    rel_path     text NOT NULL,
    sha256       text NOT NULL,
    size         bigint NOT NULL,
    kind         text NOT NULL,
    container_id bigint,
    anchor_path  text,
    member_chain text[],
    PRIMARY KEY (plan_id, pack_id, rel_path),
    FOREIGN KEY (plan_id, pack_id) REFERENCES materialize_packs(plan_id, pack_id) ON DELETE CASCADE
);
CREATE INDEX ix_materialize_files_sha ON materialize_files (plan_id, sha256);
"""

_DOWNGRADE = """
DROP TABLE IF EXISTS materialize_files;
DROP TABLE IF EXISTS materialize_packs;
DROP TABLE IF EXISTS materialize_blobs;
DROP TABLE IF EXISTS materialize_units;
DROP TABLE IF EXISTS materialize_plans;
"""


def upgrade() -> None:
    op.execute(_UPGRADE)


def downgrade() -> None:
    op.execute(_DOWNGRADE)
