"""tags: pack tag fingerprint, LLM tag-decision cache, human tag overrides

Revision ID: 0006_tags
Revises: 0004_packs
Create Date: 2026-10-03

INIT-032/SPEC-016. Chained after 0004_packs (the single head). ``packs.tags`` already exists
(0004); ``forge tags`` becomes its owner once it has run for a pack, which it records in
``tags_fingerprint`` (``forge classify`` then leaves those packs' ``tags`` alone).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0006_tags"
down_revision: str | Sequence[str] | None = "0004_packs"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE packs
            ADD COLUMN tags_fingerprint text,
            ADD COLUMN tagged_at timestamptz
        """
    )
    op.execute(
        """
        CREATE TABLE tag_decisions (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            input_fingerprint text NOT NULL,
            prompt_hash text NOT NULL,
            model text,
            verdict text NOT NULL CHECK (verdict IN ('ok', 'unsure')),
            tags text[] NOT NULL DEFAULT '{}',
            raw_tags text[] NOT NULL DEFAULT '{}',
            error text,
            evidence jsonb,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_tag_decisions_fp ON tag_decisions (input_fingerprint, prompt_hash)")
    op.execute(
        """
        CREATE TABLE tag_overrides (
            unit_key text PRIMARY KEY,
            add_tags text[],
            remove_tags text[],
            set_tags text[],
            note text,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE tag_overrides")
    op.execute("DROP TABLE tag_decisions")
    op.execute("ALTER TABLE packs DROP COLUMN tags_fingerprint, DROP COLUMN tagged_at")
